#!/bin/bash

# Confirm branch
currentBranch="$(git rev-parse --abbrev-ref HEAD)"

echo "[warn] push to remote , continue? branch name: $(tput bold)$(tput setaf 1)$currentBranch $(tput sgr0)[y/N]"

exec < /dev/tty
read answer

case $answer in
    'y' | 'yes') echo '[info] OK. push start.';;
    * ) echo '[error] push failed.';exit 1;;
esac
exit 0
