name: Chromatic

on:
  push:
    branches: [add-storybook]

jobs:
  chromatic-deployment:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: ./src/storybook/build-webpack
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
